# Generated by Django 6.0.4 on 2026-05-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orden',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado_orden',
            field=models.CharField(choices=[('En Proceso', 'En Proceso'), ('Activa', 'Activa'), ('En preparación', 'En preparación'), ('Entregada', 'Entregada'), ('Facturada', 'Facturada'), ('Cancelada', 'Cancelada')], default='En Proceso', max_length=20),
        ),
    ]
