# Generated by Django 6.0.4 on 2026-05-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_orden_impuesto_orden_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='servido',
            field=models.BooleanField(default=False),
        ),
    ]
