# Generated by Django 6.0.4 on 2026-05-16 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_detalleorden_servido'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detalleorden',
            table='Detail_Order',
        ),
    ]
