# Generated by Django 6.0.4 on 2026-05-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_empleado_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado_orden',
            field=models.CharField(choices=[('En Proceso', 'En Proceso'), ('Pendiente', 'Pendiente'), ('Activa', 'Activa'), ('En preparación', 'En preparación'), ('Entregada', 'Entregada'), ('En Caja', 'En Caja'), ('Facturada', 'Facturada'), ('Cancelada', 'Cancelada')], default='En Proceso', max_length=20),
        ),
    ]
